#  ██████╗░░█████╗░███╗░░██╗░█████╗░████████╗██╗░█████╗░███╗░░██╗███████╗██╗░░██╗███████╗░█████╗░██╗░░░██╗████████╗░█████╗░██████╗░
#  ██╔══██╗██╔══██╗████╗░██║██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║██╔════╝╚██╗██╔╝██╔════╝██╔══██╗██║░░░██║╚══██╔══╝██╔══██╗██╔══██╗
#  ██║░░██║██║░░██║██╔██╗██║███████║░░░██║░░░██║██║░░██║██╔██╗██║█████╗░░░╚███╔╝░█████╗░░██║░░╚═╝██║░░░██║░░░██║░░░██║░░██║██████╔╝
#  ██║░░██║██║░░██║██║╚████║██╔══██║░░░██║░░░██║██║░░██║██║╚████║██╔══╝░░░██╔██╗░██╔══╝░░██║░░██╗██║░░░██║░░░██║░░░██║░░██║██╔══██╗
#  ██████╔╝╚█████╔╝██║░╚███║██║░░██║░░░██║░░░██║╚█████╔╝██║░╚███║███████╗██╔╝╚██╗███████╗╚█████╔╝╚██████╔╝░░░██║░░░╚█████╔╝██║░░██║
#  ╚═════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝╚══════╝╚═╝░░╚═╝╚══════╝░╚════╝░░╚═════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝

# Список Токенов, игроков, на которых действуют донаты, а также событий, вызываемых донатами
donation-amounts:
    # Первый токен - замените строку ниже на токен со страницы https://www.donationalerts.com/dashboard/general (кнопка "показать секретный токен")
    xxxxxxxxxxxxxxxxxxxx:
        # Имя первого стримера, связанного с первым токеном
        ValeraMinecraft2003:
            # Насрать стримеру в инвентарь подписанными стаками говна
            ShitToInventory: 62
            # Выбить предмет из рук
            DropActiveItem: 65
            # Призвать Некоглая
            Nekoglai: 104
            # Дать леща - толчок вперед, который отнимет 1 сердечко
            Lesch: 67
            # Дать хлеб в количестве N кусков
            GiveBread: 82
            # Выдать определенное количество алмазов (настраивается дальше)
            GiveDiamonds: 132
            # Заспавнятся несколько сотрудников НКВД, которые заходят увести вас в ГУЛАГ
            CallNKVD: 142
            # Дать очень смачный пинок под зад, который отнимет 1.5 сердечка
            PowerKick: 152
            # В вашем инвентаре будет случайным образом заменено N слотов (по умолчанию -5)
            # на некие предметы (по умолчанию - камни)
            RandomChange: 197
            # Заспавнить крипера за спиной
            SpawnCreeper: 202
            # Уничтожить вещи, выпавшие после последней смерти
            ClearLastDeathDrop: 214
            # Все прирученные игроком кошки снова станут дикими, а прирученные волки,
            # помимо этого, еще и нападут на игрока, который был их хозяином
            TamedBecomesEnemies: 252
            # Заспавнить исполинского Иосифа Сталина, испепеляющий все вокруг
            CallStalin: 352
            # Оставить игроку лишь полсердечка
            HalfHeart: 602
            # Через N секунд (по умолчанию - 3) произойдет взрыв с радиусом M
            # (по умолчанию - 20) вокруг игрока
            BigBoom: 2002
            # Выдать целый стак алмазов
            GiveStackOfDiamonds: 2012

        # Имя второго игрока, связанного с первым токеном (просто удалите целиком эту секцию, если игрок всего один)
        VasyaPupkin:
            # Насрать стримеру в инвентарь подписанными стаками говна
            ShitToInventory: 61
            # Выбить предмет из рук
            DropActiveItem: 64
            # Призвать Некоглая
            Nekoglai: 105
            # Дать леща - толчок вперед, который отнимет 1 сердечко
            Lesch: 66
            # Дать хлеб в количестве N кусков
            GiveBread: 81
            # Выдать определенное количество алмазов (настраивается дальше)
            GiveDiamonds: 131
            # Заспавнятся несколько сотрудников НКВД, которые заходят увести вас в ГУЛАГ
            CallNKVD: 141
            # Дать очень смачный пинок под зад, который отнимет 1.5 сердечка
            PowerKick: 151
            # В вашем инвентаре будет случайным образом заменено N слотов (по умолчанию -5)
            # на некие предметы (по умолчанию - камни)
            RandomChange: 196
            # Заспавнить крипера за спиной
            SpawnCreeper: 201
            # Уничтожить вещи, выпавшие после последней смерти
            ClearLastDeathDrop: 213
            # Все прирученные игроком кошки снова станут дикими, а прирученные волки,
            # помимо этого, еще и нападут на игрока, который был их хозяином
            TamedBecomesEnemies: 251
            # Заспавнить исполинского Иосифа Сталина, испепеляющий все вокруг
            CallStalin: 351
            # Оставить игроку лишь полсердечка
            HalfHeart: 601
            # Через N секунд (по умолчанию - 3) произойдет взрыв с радиусом M
            # (по умолчанию - 20) вокруг игрока
            BigBoom: 2001
            # Выдать целый стак алмазов
            GiveStackOfDiamonds: 2011
    #Далее вы можете добавите другие токены и других игроков по образцу выше.

# Сколько блоков говна игроки будут получать в инвентарь от ShitToInventory
DirtAmount: 10
# Сколько алмазов игроки будут получать в инвентарь от GiveDiamonds
DiamondsAmount: 4
# Сколько хлеба игроки будут получать в инвентарь от GiveBread
BreadAmount: 4
# Радиус взрыва от BigBoom
BigBoomRadius: 20

# ДЛЯ КОРРЕКТНОГО ОТОБРАЖЕНИЯ КАСТОМНЫХ СКИНОВ ПЛАГИНА У ИГРОКОВ ДОЛЖЕН БЫТЬ УСТАНОВЛЕН МОД OPTIFINE - https://optifine.net/downloads
# ЧТОБЫ ОТКЛЮЧИТЬ УВЕДОМЛЕНИЯ О НЕОБХОДИМОСТИ УСТАНОВИТЬ ОПТИФАЙН, ИЗМЕНИТЕ ЗНАЧЕНИЕ НИЖЕ С "true" НА "false"
notify-about-optifine: true

# Настройка force-download-resourcepack включает/отключает загрузку ресурспака для отображения
# кастомных скинов плагина игрокам при входе на сервер
# ---------------------------------------------------------
# Эту настройку можно отключить (заменить true на false), если у всех игроков на сервере вручную установлен ресурспак плагина
# Отключение позволит сократить время входа на сервер, но игроки, не установившие ресурспак вручную не смогут видеть кастомные скины
# Ссылка на ресурспак для установки вручную (скачанный файл нужно закинуть в папку с игрой "~/.minecraft/resourcepacks/"):
# https://download.mc-packs.net/pack/5cd9b26a954b46683eeea1b7df1cc0fbe136f79f.zip
force-download-resourcepack: true

# Фильтр ников для твитча: true - вкл, false - выкл
twitch-filter: true
# Блеклист субстрок для фильтра
BlacklistedSubstrings:
    - негр
    - пидо
    - пида
    - niga
    - нигр
    - ниге
    - додик
    - петух
    - петуч
    - симп
    - simp
    - куколд
    - kukold
    - cuckold
    - fag
    - хуе
    - хуй
    - даун
    - кады
    - кадь
    - kadb
    - 4e4e
    - 4e4n
    - cheche
    - chechn
    - 4echn
    - che4n
    - 4eche
    - 4eche
# Вайтлист субстрок для фильтра
WhitelistedSubstrings:
    - книг
    - нигерия



